# Generated by Django 4.1.5 on 2023-01-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pasajero', models.CharField(max_length=80)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pasajero', models.CharField(max_length=80)),
                ('origen', models.CharField(max_length=80)),
                ('destino', models.CharField(max_length=80)),
            ],
        ),
    ]
